# Generated by Django 5.0.6 on 2024-05-31 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='elementcommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementcommandes', to='boutique.commande'),
        ),
        migrations.AlterField(
            model_name='elementcommande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementcommandes', to='boutique.produit'),
        ),
    ]
