# Generated by Django 4.2.13 on 2024-06-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0005_remove_commande_etat_commande"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="quantite",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
